export const DEFAULT_MATERIALS = [
  {
    id: 'V_3M_2080',
    name: '3M Series 2080',
    brand: '3M',
    pricePerM2: 220,
    type: 'Cast',
    line: 'Professional Graphics',
    colorTexture: 'Brilhante / Fosco / Cetim',
    durability: 'Até 8 anos',
    recommendedFor: ['Automotivo', 'Eletrodomésticos'],
    details: 'Altamente conformável, tecnologia Comply para saída de ar.',
  },
  {
    id: 'V_AVERY_SW900',
    name: 'Avery SW900',
    brand: 'Avery Dennison',
    pricePerM2: 210,
    type: 'Cast',
    line: 'Supreme Wrapping Film',
    colorTexture: 'Metallic / Gloss / Matte',
    durability: '7-12 anos',
    recommendedFor: ['Automotivo'],
    details: 'Excelente reposicionamento e deslizamento.',
  },
  {
    id: 'V_ALLTAK_DECOR',
    name: 'Alltak Decor Wood',
    brand: 'Alltak',
    pricePerM2: 85,
    type: 'Calandrado',
    line: 'Decorativo',
    colorTexture: 'Madeiras Variadas',
    durability: 'Até 5 anos (interno)',
    recommendedFor: ['Móveis', 'Parede'],
    details: 'Textura real de madeira, alta aderência.',
  },
  {
    id: 'V_ORACAL_651',
    name: 'Oracal 651',
    brand: 'Orafol',
    pricePerM2: 45,
    type: 'Calandrado',
    line: 'Intermediário',
    colorTexture: 'Cores Sólidas',
    durability: 'Até 6 anos',
    recommendedFor: ['Eletrodomésticos', 'Sinalização'],
    details: 'Ideal para superfícies planas ou curvas simples.',
  },
  {
    id: 'V_PPF_ULTRA',
    name: 'Suntek PPF Ultra',
    brand: 'SunTek',
    pricePerM2: 550,
    type: 'PPF',
    line: 'Protection Film',
    colorTexture: 'Transparente / Gloss',
    durability: '10 anos',
    recommendedFor: ['Automotivo'],
    details: 'Auto-regeneração (self-healing) e proteção contra impactos.',
  },
];

export const VEHICLES_DATABASE = [
  {
    id: 'V1',
    make: 'Honda',
    model: 'Civic G10',
    year: '2020',
    size: 'Médio (Sedan/SUV Compacto)',
    partMeasurements: {
      CAP: { width: 1.52, length: 2.0 },
      TET: { width: 1.52, length: 2.2 },
      MAL: { width: 1.52, length: 1.5 },
      PCD: { width: 1.52, length: 1.2 },
      PCE: { width: 1.52, length: 1.2 },
      PTD: { width: 1.52, length: 1.8 },
      PTE: { width: 1.52, length: 1.8 },
      PDD: { width: 1.52, length: 1.5 },
      PDE: { width: 1.52, length: 1.5 },
      PTD_DOOR: { width: 1.52, length: 1.4 },
      PTE_DOOR: { width: 1.52, length: 1.4 },
      PCD_BUMP: { width: 1.52, length: 2.5 },
      PCT_BUMP: { width: 1.52, length: 2.5 },
      RET_D: { width: 0.5, length: 0.5 },
      RET_E: { width: 0.5, length: 0.5 },
      SAI_D: { width: 0.3, length: 2.0 },
      SAI_E: { width: 0.3, length: 2.0 },
      COL: { width: 0.2, length: 1.0 },
      MAC_D: { width: 0.5, length: 0.5 },
    },
  },
  {
    id: 'V2',
    make: 'Toyota',
    model: 'Corolla',
    year: '2022',
    size: 'Médio (Sedan/SUV Compacto)',
    partMeasurements: {
      CAP: { width: 1.52, length: 1.8 },
      TET: { width: 1.52, length: 2.1 },
      MAL: { width: 1.52, length: 1.4 },
      PCD: { width: 1.52, length: 1.1 },
      PCE: { width: 1.52, length: 1.1 },
      PTD: { width: 1.52, length: 1.7 },
      PTE: { width: 1.52, length: 1.7 },
      PDD: { width: 1.52, length: 1.4 },
      PDE: { width: 1.52, length: 1.4 },
      PTD_DOOR: { width: 1.52, length: 1.3 },
      PTE_DOOR: { width: 1.52, length: 1.3 },
      PCD_BUMP: { width: 1.52, length: 2.4 },
      PCT_BUMP: { width: 1.52, length: 2.4 },
      RET_D: { width: 0.4, length: 0.4 },
      RET_E: { width: 0.4, length: 0.4 },
      SAI_D: { width: 0.3, length: 1.9 },
      SAI_E: { width: 0.3, length: 1.9 },
      COL: { width: 0.2, length: 0.9 },
      MAC_D: { width: 0.4, length: 0.4 },
    },
  },
  {
    id: 'V3',
    make: 'Volkswagen',
    model: 'Gol G7',
    year: '2019',
    size: 'Pequeno (Hatch/Compacto)',
    partMeasurements: {
      CAP: { width: 1.52, length: 1.5 },
      TET: { width: 1.52, length: 1.8 },
      MAL: { width: 1.52, length: 1.2 },
      PCD: { width: 1.52, length: 1.0 },
      PCE: { width: 1.52, length: 1.0 },
      PTD: { width: 1.52, length: 1.5 },
      PTE: { width: 1.52, length: 1.5 },
      PDD: { width: 1.52, length: 1.3 },
      PDE: { width: 1.52, length: 1.3 },
      PCD_BUMP: { width: 1.52, length: 2.0 },
      PCT_BUMP: { width: 1.52, length: 2.0 },
      RET_D: { width: 0.4, length: 0.4 },
      RET_E: { width: 0.4, length: 0.4 },
      SAI_D: { width: 0.2, length: 1.6 },
      SAI_E: { width: 0.2, length: 1.6 },
    },
  },
];

export const APPLIANCES_DATABASE = [
  {
    id: 'A1',
    make: 'Brastemp',
    model: 'Inox inverse 443L',
    type: 'Geladeira',
    width: 0.7,
    height: 1.84,
    depth: 0.75,
  },
  {
    id: 'A2',
    make: 'Samsung',
    model: 'Side by Side 501L',
    type: 'Geladeira',
    width: 0.91,
    height: 1.78,
    depth: 0.71,
  },
  {
    id: 'A3',
    make: 'Electrolux',
    model: 'Top Load 12kg',
    type: 'Máquina de Lavar',
    width: 0.66,
    height: 1.02,
    depth: 0.72,
  },
  {
    id: 'A4',
    make: 'LG',
    model: 'Washtower',
    type: 'Máquina de Lavar',
    width: 0.61,
    height: 1.89,
    depth: 0.66,
  },
];
