export interface CountryDial {
  iso2: string;
  name: string;
  dial: string;
  flag: string;
  /** # = dígito; usado na máscara de exibição */
  mask?: string;
}

/** Brasil primeiro; demais países em ordem alfabética (nome em português). */
export const COUNTRY_PHONE_LIST: CountryDial[] = [
  { iso2: 'BR', name: 'Brasil', dial: '+55', flag: '🇧🇷', mask: '(##) #####-####' },
  { iso2: 'AF', name: 'Afeganistão', dial: '+93', flag: '🇦🇫' },
  { iso2: 'ZA', name: 'África do Sul', dial: '+27', flag: '🇿🇦' },
  { iso2: 'AL', name: 'Albânia', dial: '+355', flag: '🇦🇱' },
  { iso2: 'DE', name: 'Alemanha', dial: '+49', flag: '🇩🇪', mask: '#### ########' },
  { iso2: 'AD', name: 'Andorra', dial: '+376', flag: '🇦🇩' },
  { iso2: 'AO', name: 'Angola', dial: '+244', flag: '🇦🇴' },
  { iso2: 'SA', name: 'Arábia Saudita', dial: '+966', flag: '🇸🇦' },
  { iso2: 'DZ', name: 'Argélia', dial: '+213', flag: '🇩🇿' },
  { iso2: 'AR', name: 'Argentina', dial: '+54', flag: '🇦🇷', mask: '(##) ####-####' },
  { iso2: 'AM', name: 'Armênia', dial: '+374', flag: '🇦🇲' },
  { iso2: 'AU', name: 'Austrália', dial: '+61', flag: '🇦🇺', mask: '#### ### ###' },
  { iso2: 'AT', name: 'Áustria', dial: '+43', flag: '🇦🇹' },
  { iso2: 'AZ', name: 'Azerbaijão', dial: '+994', flag: '🇦🇿' },
  { iso2: 'BD', name: 'Bangladesh', dial: '+880', flag: '🇧🇩' },
  { iso2: 'BE', name: 'Bélgica', dial: '+32', flag: '🇧🇪' },
  { iso2: 'BO', name: 'Bolívia', dial: '+591', flag: '🇧🇴' },
  { iso2: 'BA', name: 'Bósnia e Herzegovina', dial: '+387', flag: '🇧🇦' },
  { iso2: 'BG', name: 'Bulgária', dial: '+359', flag: '🇧🇬' },
  { iso2: 'CA', name: 'Canadá', dial: '+1', flag: '🇨🇦', mask: '(###) ###-####' },
  { iso2: 'QA', name: 'Catar', dial: '+974', flag: '🇶🇦' },
  { iso2: 'KZ', name: 'Cazaquistão', dial: '+7', flag: '🇰🇿' },
  { iso2: 'CL', name: 'Chile', dial: '+56', flag: '🇨🇱', mask: '# #### ####' },
  { iso2: 'CN', name: 'China', dial: '+86', flag: '🇨🇳', mask: '### #### ####' },
  { iso2: 'CY', name: 'Chipre', dial: '+357', flag: '🇨🇾' },
  { iso2: 'CO', name: 'Colômbia', dial: '+57', flag: '🇨🇴', mask: '### ### ####' },
  { iso2: 'KR', name: 'Coreia do Sul', dial: '+82', flag: '🇰🇷', mask: '##-####-####' },
  { iso2: 'CR', name: 'Costa Rica', dial: '+506', flag: '🇨🇷' },
  { iso2: 'HR', name: 'Croácia', dial: '+385', flag: '🇭🇷' },
  { iso2: 'CU', name: 'Cuba', dial: '+53', flag: '🇨🇺' },
  { iso2: 'DK', name: 'Dinamarca', dial: '+45', flag: '🇩🇰', mask: '## ## ## ##' },
  { iso2: 'EG', name: 'Egito', dial: '+20', flag: '🇪🇬' },
  { iso2: 'SV', name: 'El Salvador', dial: '+503', flag: '🇸🇻' },
  { iso2: 'AE', name: 'Emirados Árabes', dial: '+971', flag: '🇦🇪', mask: '## ### ####' },
  { iso2: 'EC', name: 'Equador', dial: '+593', flag: '🇪🇨' },
  { iso2: 'SK', name: 'Eslováquia', dial: '+421', flag: '🇸🇰' },
  { iso2: 'SI', name: 'Eslovênia', dial: '+386', flag: '🇸🇮' },
  { iso2: 'ES', name: 'Espanha', dial: '+34', flag: '🇪🇸', mask: '### ## ## ##' },
  { iso2: 'US', name: 'Estados Unidos', dial: '+1', flag: '🇺🇸', mask: '(###) ###-####' },
  { iso2: 'EE', name: 'Estônia', dial: '+372', flag: '🇪🇪' },
  { iso2: 'ET', name: 'Etiópia', dial: '+251', flag: '🇪🇹' },
  { iso2: 'PH', name: 'Filipinas', dial: '+63', flag: '🇵🇭' },
  { iso2: 'FI', name: 'Finlândia', dial: '+358', flag: '🇫🇮' },
  { iso2: 'FR', name: 'França', dial: '+33', flag: '🇫🇷', mask: '# ## ## ## ##' },
  { iso2: 'GE', name: 'Geórgia', dial: '+995', flag: '🇬🇪' },
  { iso2: 'GH', name: 'Gana', dial: '+233', flag: '🇬🇭' },
  { iso2: 'GR', name: 'Grécia', dial: '+30', flag: '🇬🇷' },
  { iso2: 'GT', name: 'Guatemala', dial: '+502', flag: '🇬🇹' },
  { iso2: 'HN', name: 'Honduras', dial: '+504', flag: '🇭🇳' },
  { iso2: 'HK', name: 'Hong Kong', dial: '+852', flag: '🇭🇰' },
  { iso2: 'HU', name: 'Hungria', dial: '+36', flag: '🇭🇺' },
  { iso2: 'IN', name: 'Índia', dial: '+91', flag: '🇮🇳', mask: '##### #####' },
  { iso2: 'ID', name: 'Indonésia', dial: '+62', flag: '🇮🇩' },
  { iso2: 'IQ', name: 'Iraque', dial: '+964', flag: '🇮🇶' },
  { iso2: 'IE', name: 'Irlanda', dial: '+353', flag: '🇮🇪' },
  { iso2: 'IL', name: 'Israel', dial: '+972', flag: '🇮🇱' },
  { iso2: 'IT', name: 'Itália', dial: '+39', flag: '🇮🇹', mask: '### ### ####' },
  { iso2: 'JP', name: 'Japão', dial: '+81', flag: '🇯🇵', mask: '##-####-####' },
  { iso2: 'JO', name: 'Jordânia', dial: '+962', flag: '🇯🇴' },
  { iso2: 'KW', name: 'Kuwait', dial: '+965', flag: '🇰🇼' },
  { iso2: 'LB', name: 'Líbano', dial: '+961', flag: '🇱🇧' },
  { iso2: 'LY', name: 'Líbia', dial: '+218', flag: '🇱🇾' },
  { iso2: 'LT', name: 'Lituânia', dial: '+370', flag: '🇱🇹' },
  { iso2: 'LU', name: 'Luxemburgo', dial: '+352', flag: '🇱🇺' },
  { iso2: 'MY', name: 'Malásia', dial: '+60', flag: '🇲🇾' },
  { iso2: 'MA', name: 'Marrocos', dial: '+212', flag: '🇲🇦' },
  { iso2: 'MX', name: 'México', dial: '+52', flag: '🇲🇽', mask: '## #### ####' },
  { iso2: 'MZ', name: 'Moçambique', dial: '+258', flag: '🇲🇿' },
  { iso2: 'MD', name: 'Moldávia', dial: '+373', flag: '🇲🇩' },
  { iso2: 'MC', name: 'Mônaco', dial: '+377', flag: '🇲🇨' },
  { iso2: 'MN', name: 'Mongólia', dial: '+976', flag: '🇲🇳' },
  { iso2: 'NA', name: 'Namíbia', dial: '+264', flag: '🇳🇦' },
  { iso2: 'NP', name: 'Nepal', dial: '+977', flag: '🇳🇵' },
  { iso2: 'NI', name: 'Nicarágua', dial: '+505', flag: '🇳🇮' },
  { iso2: 'NG', name: 'Nigéria', dial: '+234', flag: '🇳🇬' },
  { iso2: 'NO', name: 'Noruega', dial: '+47', flag: '🇳🇴', mask: '### ## ###' },
  { iso2: 'NZ', name: 'Nova Zelândia', dial: '+64', flag: '🇳🇿' },
  { iso2: 'NL', name: 'Países Baixos', dial: '+31', flag: '🇳🇱', mask: '# ########' },
  { iso2: 'PA', name: 'Panamá', dial: '+507', flag: '🇵🇦' },
  { iso2: 'PY', name: 'Paraguai', dial: '+595', flag: '🇵🇾' },
  { iso2: 'PE', name: 'Peru', dial: '+51', flag: '🇵🇪', mask: '### ### ###' },
  { iso2: 'PL', name: 'Polônia', dial: '+48', flag: '🇵🇱', mask: '### ### ###' },
  { iso2: 'PT', name: 'Portugal', dial: '+351', flag: '🇵🇹', mask: '### ### ###' },
  { iso2: 'GB', name: 'Reino Unido', dial: '+44', flag: '🇬🇧', mask: '#### ######' },
  { iso2: 'CZ', name: 'República Tcheca', dial: '+420', flag: '🇨🇿' },
  { iso2: 'DO', name: 'República Dominicana', dial: '+1', flag: '🇩🇴', mask: '(###) ###-####' },
  { iso2: 'RO', name: 'Romênia', dial: '+40', flag: '🇷🇴' },
  { iso2: 'RU', name: 'Rússia', dial: '+7', flag: '🇷🇺', mask: '(###) ###-##-##' },
  { iso2: 'SN', name: 'Senegal', dial: '+221', flag: '🇸🇳' },
  { iso2: 'RS', name: 'Sérvia', dial: '+381', flag: '🇷🇸' },
  { iso2: 'SG', name: 'Singapura', dial: '+65', flag: '🇸🇬', mask: '#### ####' },
  { iso2: 'SY', name: 'Síria', dial: '+963', flag: '🇸🇾' },
  { iso2: 'SE', name: 'Suécia', dial: '+46', flag: '🇸🇪', mask: '##-### ## ##' },
  { iso2: 'CH', name: 'Suíça', dial: '+41', flag: '🇨🇭', mask: '## ### ## ##' },
  { iso2: 'TH', name: 'Tailândia', dial: '+66', flag: '🇹🇭' },
  { iso2: 'TW', name: 'Taiwan', dial: '+886', flag: '🇹🇼' },
  { iso2: 'TZ', name: 'Tanzânia', dial: '+255', flag: '🇹🇿' },
  { iso2: 'TN', name: 'Tunísia', dial: '+216', flag: '🇹🇳' },
  { iso2: 'TR', name: 'Turquia', dial: '+90', flag: '🇹🇷', mask: '### ### ## ##' },
  { iso2: 'UA', name: 'Ucrânia', dial: '+380', flag: '🇺🇦' },
  { iso2: 'UY', name: 'Uruguai', dial: '+598', flag: '🇺🇾', mask: '#### ####' },
  { iso2: 'VE', name: 'Venezuela', dial: '+58', flag: '🇻🇪' },
  { iso2: 'VN', name: 'Vietnã', dial: '+84', flag: '🇻🇳' },
];

export function findCountryByDial(dial: string): CountryDial | undefined {
  return COUNTRY_PHONE_LIST.find((c) => c.dial === dial);
}

export function findCountryByIso(iso2: string): CountryDial | undefined {
  return COUNTRY_PHONE_LIST.find((c) => c.iso2 === iso2);
}
